server:
  port: 8089
spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://mysql:3306/core_arch?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000

  redis:
    host: redis
    port: 6379
    timeout: 3000ms

  mybatis:
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.example.entity
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      lazy-loading-enabled: true
