version: '3.8'

services:
  server-auth:
    build:
      context: ./server-auth
      dockerfile: Dockerfile
    image: server-auth:1.0
    container_name: server-auth
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    restart: unless-stopped

  server-user:
    build:
      context: ./server-user
      dockerfile: Dockerfile
    image: server-user:1.0
    container_name: server-user
    ports:
      - "8090:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: core_arch
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
